version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "5173:5173"
    networks:
      - mern
    environment:
      VITE_API_URL: "http://backend:5050" # Set the backend API URL for frontend usage
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5050:5050"
    networks:
      - mern
    depends_on:
      - mongo
      - db
    environment:
      MONGO_URI: "mongodb://mongo:27017/mydb"  # MongoDB URI
      POSTGRES_URI: "postgres://myuser:mypassword@db:5432/mydb"  # Postgres URI

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - mongo-data:/data/db

  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - mern
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  mern:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  postgres-data:
    driver: local
